### ISSUE TITLE
Replace Java POJOs with Kotlin data classes

### ISSUE THREAD

**Issue by YassinAJDI** [YassinAJDI/PopularMovies#4]
It will be nice to replace all those Java POJOs [in this package](https://github.com/YassinAJDI/PopularMovies/tree/master/app/src/main/java/com/ajdi/yassin/popularmovies/data/local/model) with Kotlin data classes: https://kotlinlang.org/docs/reference/data-classes.html

**Comment by anhanh11001** [comment]
I would like to work on this

**Comment by YassinAJDI** [comment]
Hello @anhanh11001, Thank you for showing interest in this issue. 
Please go ahead and make a fork then submit your pull request. I will be happy to merge it during 1-30 October to get you some credit toward the Hacktoberfest event.
