### ISSUE TITLE
I think it would be better if I put in a viewpager.

### ISSUE THREAD

**Issue by saechimdaeki** [YassinAJDI/PopularMovies#7]
May I change the botom Nav and Fragment a little to make them turn into left and right swipe with a viewpager between Discover and Favorites Fragment?

**Comment by YassinAJDI** [comment]
@saechimdaeki I don't think you do need a `VIewPager` for that. You can use some animation for Fragment in and Fragment out. Another option which is recommended is to use `Navigation` component which will make this very easy.

**Comment by saechimdaeki** [comment]
너의 말은 bottom nav를 통해 fragment를 이동할때 애니메이션 효과가 있으면 좋겠다라는뜻?

**Comment by saechimdaeki** [comment]
Do you mean that when you move Fragment through botom Nav, you want to have animation effect?

**Comment by saechimdaeki** [comment]
@YassinAJDI Well, I will start with some Fragments animation or something.

**Comment by 2tanayk** [comment]
May I work on this issue?and it would be really great if I get more details regarding this issue :)

**Comment by saechimdaeki** [comment]
@2tanayk I think you can send an email directly to the master after opening the PR after doing it once.
Because YassinAJDI, the master, doesn't seem to do GitHub anymore.

**Comment by 2tanayk** [comment]
Ohh

**Comment by localbusinesscompany2** [comment]
https://github.com/Significant-Gravitas/Auto-GPT

**Comment by localbusinesscompany2** [comment]
> https://github.com/Significant-Gravitas/Auto-GPT

Auto GPT
